services:
  client:
    container_name: post_client
    build: ../Client
    image: debug_client
    ports:
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ../Client
        target: /code
    command: ['http-server']

  api:
    container_name: post_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=librarypass
      - PGDATABASE=library
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: post_db
    image: postgres:12.4
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=librarypass
volumes:
  dbdata:
networks:
  default:
    name: post_api
