version: '3'
services:
  api:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code

  db:
    image: postgres:12.4
    environment: 
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=futureproof-pass
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
